sonar.projectKey=devsecops-dashboard
sonar.projectName=devsecops-dashboard

sonar.sources=frontend/src

sonar.exclusions=
frontend/src/pages/Dashboard.jsx,
frontend/src/pages/Findings.jsx,
frontend/src/pages/TrivyDetails.jsx,
frontend/src/pages/SonarDetails.jsx,
frontend/src/pages/SnykDetails.jsx,
frontend/src/VulnerableApp.jsx,
frontend/src/components/IssueModal.jsx,
frontend/src/components/IssueCard.jsx

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
