sonar.projectKey=devsecops-dashboard

sonar.projectName=DevSecOps Dashboard

sonar.sources=.

sonar.sourceEncoding=UTF-8

sonar.host.url=http://host.docker.internal:9000

sonar.token=squ_88cf1f2d8e0c36e72ab8550bf4df982bc102a5d9
