sonar.projectKey=devsecops-dashboard
sonar.sources=.
sonar.host.url=http://localhost:9000
sonar.python.coverage.reportPaths=coverage.xml
sonar.projectKey=devsecops-dashboard
sonar.sources=.
sonar.python.coverage.reportPaths=coverage.xml
