name: DevSecOps Pipeline

on:
push:
branches:
- main

pull_request:
branches:
- main

jobs:
gate1:
runs-on: ubuntu-latest

```
steps:
  - name: Checkout Source
    uses: actions/checkout@v4

  - name: Debug Structure
    run: |
      pwd
      ls -la
      find . -name package.json

  - name: Setup NodeJS
    uses: actions/setup-node@v4
    with:
      node-version: 20

  - name: Install Dependencies
    run: |
      cd frontend
      npm install

  - name: Run Unit Test
    run: |
      cd frontend
      npm test -- --watchAll=false

  - name: Build Application
    run: |
      cd frontend
      npm run build
```
